### ISSUE TITLE
select! Usage

### ISSUE THREAD

**Issue by gsquire** [crossbeam-rs/crossbeam#350] opened 2019-03-26 23:54 UTC
I am experimenting with using channels to configure a timeout when running an external command. Below is an example program:

```rust
use std::process::Command;
use std::thread;
use std::time::Duration;

use crossbeam_channel::{select, unbounded};

fn main() {
    let (tx, rx) = unbounded();
    let (s, r) = unbounded();

    let handle = thread::spawn(move || {
        if let Ok(mut child) = Command::new("sleep").arg("2").spawn() {
            println!("before select in thread");
            select! {
                recv(r) -> _ => {
                    println!("got notification to kill process");
                    child.kill().expect("kill the process");
                    println!("killed");
                },
                send(tx, child.wait().expect("to wait")) -> _ => println!("notified that we are done"),
            }
            println!("after select in thread");
        } else {
            println!("error spawning the command");
        }
    });

    select! {
        recv(rx) -> _ => println!("did not timeout"),
        default(Duration::from_millis(100)) => {
            println!("timed out");
            s.send(()).expect("to send a kill notification");
            println!("sent notification to kill");
        },
    }

    handle.join().expect("to join thread");
}
```

When running this, I would expect the `default` case to send an empty message on the `s` channel which would then terminate my `Command`. However, it waits for the `send` operation on `tx` each time.

From my understanding of `select!`, it will wait until an operation can proceed. Therefore it should fire when the `recv` happens on `r`. It doesn't seem to ever happen though. I may be missing something or have a typo somewhere but I am pretty sure this should work.

Where am I going wrong? Thanks!

**Comment by stjepang** [comment] 2019-03-27 10:54
It seems to me the problem is with this line:

```rust
send(tx, child.wait().expect("to wait")) -> _ => println!("notified that we are done"),
```

Sender `tx` is ready for sending so this select case fires immediately. The message then gets produced by `child.wait().expect("to wait")`, which simply blocks until the process finishes.

Here are some solutions that come to mind:

1. Call `child.try_wait()` in a loop to check whether the process has completed. Sleep for 10 ms or so at every step in order not to burn CPU spinning the whole time.

2. Use the [`subprocess`](https://docs.rs/subprocess/0.1.18/subprocess/index.html) crate, which can wait for the process with a timeout.

3. Get the ID of the process, block on it with `child.wait()` in a dedicated thread, and call `libc::kill(id)` when the timeout is reached.

**Comment by gsquire** [comment] 2019-03-27 16:07
> Sender tx is ready for sending so this select case fires immediately.

That is because it's unbounded right?

Thanks for the tips. It seems that 2 is the best option in this case since it won't require busy looping.

**Comment by stjepang** [comment] 2019-03-27 16:12
> That is because it's unbounded right?

Yes, exactly.

All right, I'm closing this issue. If you have any other questions, don't hesitate to ask! :)

**Closed by stjepang** 2019-03-27 16:12 UTC
Labels: crossbeam-channel, question
