### ISSUE TITLE
Is it safe to provide a lock free clone() method for AtomicCell<T: Clone>?

### ISSUE THREAD

**Issue by TennyZhuang** [crossbeam-rs/crossbeam#716] opened 2021-07-06 12:32 UTC
A useful  usage is:

```rust
let v: AtomicCell<Box<String>> = AtomicCell::new(Box::new(String::from("abc")));
// thead 1
let s = v.clone();
// thread 2
v.store(Box::new(String::from("def")));
```

So that we can load a snapshot and update for a complex struct concurrently with lock free implementation.

String is Clone so that Box<String> is also Clone, and fundamental types such as Box/Rc/... can be swapped lock free.

Is it possible to provide a lock free implementation such as:

```rust
impl<T: Clone> Clone for AtomicCell<T>
```

**Comment by taiki-e** [comment] 2021-07-06 12:37
I think this is a duplicate of #593

> It may be possible to implement it if specialization is stable, but it cannot be lock-free because non-Copy types cannot be represented as atomic types of the standard library.
> There are also issues related to destructors and interior mutability. See https://users.rust-lang.org/t/why-does-cell-require-copy-instead-of-clone/5769 for more.
> 
> In any case, I don't think it's very useful because non-lock-free AtomicCell is actually similar to using a mutex.

**Closed by taiki-e** 2021-07-06 12:37 UTC

**Comment by TennyZhuang** [comment] 2021-07-06 12:45
> because non-Copy types cannot be represented as atomic types of the standard library.

Cannot understand it, some pointer struct, such as Arc<T>, Box<T: Clone> is not Copy, but seems like can be swapped lock free

**Comment by taiki-e** [comment] 2021-07-06 13:08
Why do you think they can be swapped lock-free?

**Comment by ZhennanWu** [comment] 2022-03-08 03:45
> In any case, I don't think it's very useful because non-lock-free AtomicCell is actually similar to using a mutex.

Actually I think this can be useful for downstream library developers. In essence, what values most behind `AtomicCell` is the lock/atomic switching infrasturcture based on incoming types. However, downstream library developers are forced to either limit themselves to `Copy` (which is not realistic) or effectively forking the entire infrasturcture. It's a small addition on crossbeam crate itself but creates a whole new set of library use cases.

**Comment by taiki-e** [comment] 2022-03-17 06:47
> Maybe a new method `AtomicCell::load_full` just like `arc_swap` did [load_full](https://docs.rs/arc-swap/latest/arc_swap/struct.ArcSwapAny.html#method.load_full)?

One reason why `AtomicCell<T: Clone & !Copy>::load` cannot be implemented lock-free is that `T` must be protected from another thread's writer during the clone. So, even if a new method was introduced, that would not help much because `swap` and `store` would also need to be specialized.

And note that if `AtomicCell<T: Clone & !Copy>::load` is supported, `swap` and `store` for that type will also no longer be lock-free (they are currently lock-free). (Even if you use [the way that arc-swap does](https://github.com/vorner/arc-swap/blob/master/src/debt/mod.rs), `swap` and `store` have additional costs.)

> effectively forking the entire infrasturcture

Is there a concrete example of this? (I'm concerned that may be unsound.)
