### ISSUE TITLE
Package is failing on m1 macbook pro

### ISSUE THREAD

**Issue by codeyash** [crossbeam-rs/crossbeam#705] opened 2021-05-28 22:04 UTC
Compiling crossbeam-channel v0.5.1
error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /Users/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.4/src/internal.rs:620:59
    |
620 |         let local_ptr = (entry as *const Entry as usize - offset_of!(Local, entry)) as *const Local;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /Users/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.4/src/internal.rs:613:59
    |
613 |         let entry_ptr = (local as *const Local as usize + offset_of!(Local, entry)) as *const Entry;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `crossbeam-epoch`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...

**Comment by taiki-e** [comment] 2021-05-29 10:13
Duplicate of #678 and #679. It can be fixed by using nightly-2021-01-31 or later. See also https://github.com/crossbeam-rs/crossbeam/issues/678#issuecomment-811914871.

**Closed by taiki-e** 2021-05-29 10:13 UTC
