### ISSUE TITLE
Hello world example for channels is broken

### ISSUE THREAD

**Issue by alexpyattaev** [crossbeam-rs/crossbeam#939] opened 2022-12-15 10:27 UTC
The example as provided on docs.rs does not actually work:
``` rust
use crossbeam_channel::unbounded; // BUG - this use will not work!

// Create a channel of unbounded capacity.
let (s, r) = unbounded();

// Send a message into the channel.
s.send("Hello, world!").unwrap();

// Receive the message from the channel.
assert_eq!(r.recv(), Ok("Hello, world!"));
```

Not that it is a major issue, but may take a while for someone to figure out they are not going insane and the correct use is 
``` rust
use crossbeam::channel::unbounded;
```

Not a major issue but given that this is literally the "Hello World" example it may not project the best image to a new user=)

**Comment by taiki-e** [comment] 2022-12-15 10:33
Duplicate of https://github.com/crossbeam-rs/crossbeam/issues/529.

**Closed by taiki-e** 2022-12-15 10:33 UTC
