### ISSUE TITLE
crossbeam work with tokio not perfect fit

### ISSUE THREAD

**Issue by bartliu827** [crossbeam-rs/crossbeam#902] opened 2022-08-29 11:55 UTC
the following test code will block on rx.await.
crossbeam-channel = "0.5.6"

use crossbeam_channel as channel;
    use tokio::sync::oneshot;
    #[tokio::test]
    async fn test_crossbeam_oneshot() {
        let (sender, receiver) = channel::unbounded::<oneshot::Sender<String>>();
        tokio::spawn(async move {
            while let Ok(tx) = receiver.recv() {
                tx.send("hello".to_string());
            }
        });
        let (tx, rx) = oneshot::channel::<String>();
        sender.send(tx);
        let result = rx.await;
        println!("======after recv:  {}", result.unwrap());
    }

**Comment by taiki-e** [comment] 2022-08-29 11:57
Duplicate of #896

**Closed by taiki-e** 2022-08-29 11:57 UTC
