### ISSUE TITLE
nightly rust error

### ISSUE THREAD

**Issue by jianshu93** [crossbeam-rs/crossbeam#806] opened 2022-03-20 07:26 UTC
Hello Team,
the newest nightly rust v1.61, I have the following error:

error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /Users/jianshuzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.8/src/atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

How should I solve this? I have a SIMD implementation depends on nightly rust.

Thanks,

Jianshu

**Comment by taiki-e** [comment] 2022-03-20 07:28
Duplicate of #803

**Closed by taiki-e** 2022-03-20 07:28 UTC
