### ISSUE TITLE
Expose is_disconnected for Sender

### ISSUE THREAD

**Issue by John-Nagle** [crossbeam-rs/crossbeam#943] opened 2022-12-24 02:05 UTC
The internal channel "flavors" have **is_disconnected()** now, but that's not exposed at the **Sender** level.

Use case: find out if the receive end of a channel has gone dead without trying to send something.

**Comment by taiki-e** [comment] 2022-12-24 04:23
Duplicate of #586

**Closed by taiki-e** 2022-12-24 04:23 UTC
