### ISSUE TITLE
Need help maintaining crossbeam

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam#568] opened 2020-09-16 15:17 UTC
Hi all, as you may have noticed, I haven't had the time or energy to meaningfully contribute to Crossbeam in a while. My peak effort spanned 2017 and 2018, but then 2019 and 2020 were quite silent from my side.

There's a bunch of reasons for my absence. A big one is burnout. But also, my focus has shifted onto other kinds of projects (mainly around async) and, over time, I have found less and less of crossbeam dependencies in my projects. Before, I used to be into crazy lock-free data structures, but these days I tend to prefer sticking with simple and safe code instead.

Crossbeam has always been a team effort with me in the role of a 'lead'. So the question is: Is there someone who would like to step into this role? Do we even need this role, considering that a number of people other than me have full permissions and have been publishing crates?

Pinging some people that I believe might be interested, although I'm surely forgetting someone: @jeehoonkang, @taiki-e, @Vtec234, @schets

Anyways, I'll keep this brief. Let's figure out how to keep this project running. I'm happy to answer any questions.

**Comment by jeehoonkang** [comment] 2020-12-30 04:13
- I think we can safely assume @taiki-e and I are leading the maintenance of crossbeam.  @taiki-e is it correct? :)
- @stjepang would you please give us all the permissions, including those on github, crates.io, discord, ...

**Comment by stjepang** [comment] 2020-12-30 13:27
> * @stjepang would you please give us all the permissions, including those on github, crates.io, discord, ...

I believe everything has been transferred, but let me know if I'm missing anything specific.

**Comment by taiki-e** [comment] 2021-01-01 14:03
> @taiki-e is it correct? :)

@jeehoonkang Yes.

> I believe everything has been transferred

@stjepang Thanks, I confirmed it.

**Comment by taiki-e** [comment] 2021-01-01 15:24
> * all the permissions, including those on github, crates.io, discord

@jeehoonkang 
- I sent an ownership invitation of [crossbeam-queue](https://crates.io/crates/crossbeam-queue) because it seems your name isn't on the list of owners of it.
- I'm currently the server owner of crossbeam's discord server. I would like to add you to the admin, but it seems you have 3 accounts and I'm not sure which one is your real account...

**Comment by jeehoonkang** [comment] 2021-01-03 02:51
@taiki-e My representative email address is `jeehoon.kang@kaist.ac.kr`.

Closing this, because I think the issue is now resolved.. :)

**Closed by jeehoonkang** 2021-01-03 02:51 UTC
