### ISSUE TITLE
consider adding `is_disconnected` method to Receiver type

### ISSUE THREAD

**Issue by choleraehyq** [crossbeam-rs/crossbeam#1009] opened 2023-08-07 08:37 UTC
Sometimes we need to check whether the receiver is disconnected rather than empty, to make sure there will not be any other msg being sent to this receiver. 

The semantic of this method is quite clear. For `ReceiverFlavor::Array` `ReceiverFlavor::List` `ReceiverFlavor::Zero`, `is_disconnected` will return true when corresponding `Sender` is dropped; for `ReceiverFlavor::Tick`, `is_disconnected` will always be false; for `ReceiverFlavor::At`, `is_disconnected` will be true after it's fired; for `ReceiverFlavor::Never`, `is_disconnected` will always be true.

**Comment by taiki-e** [comment] 2023-08-07 14:36
Duplicate of #586.

**Closed by taiki-e** 2023-08-07 14:36 UTC
