### ISSUE TITLE
crossbeam-channel v0.3.9 fails to compile

### ISSUE THREAD

**Issue by RalfJung** [crossbeam-rs/crossbeam#435] opened 2019-10-18 09:08 UTC
After bumping the rustc-ap-* crates in rustfmt, I get
```
error[E0432]: unresolved import `crossbeam_utils::atomic`
 --> /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-channel-0.3.9/src/flavors/tick.rs:8:22
  |
8 | use crossbeam_utils::atomic::AtomicCell;
  |                      ^^^^^^ could not find `atomic` in `crossbeam_utils`
```
The dependency tree looks as follows:
```
crossbeam-channel v0.3.9
└── crossbeam-utils v0.6.6
    ├── cfg-if v0.1.10
    └── lazy_static v1.4.0
```

**Comment by RalfJung** [comment] 2019-10-18 09:11
I was able to fix the build with
```
cargo update -p crossbeam-utils --precise 0.6.5
```

**Comment by RalfJung** [comment] 2019-10-18 09:14
Actually turns out that even without bumping anything, rustfmt master with its current lockfile just doesn't build here...?
```
$ rustc --version
rustc 1.40.0-nightly (237d54ff6 2019-10-15)
```

**Comment by RalfJung** [comment] 2019-10-18 14:00
https://github.com/rust-lang/rust/issues/65424 explains what is going on: the crate was relying on a nightly feature that got changed.

**Comment by mati865** [comment] 2019-10-20 18:17
Duplicate of https://github.com/crossbeam-rs/crossbeam/issues/434, fixed by https://github.com/crossbeam-rs/crossbeam/commit/5b5d727fcd2616b1f5314db03f4e6b96791a303d but there is no new release yet.

**Comment by kurtlawrence** [comment] 2019-10-30 07:43
Is there an eta on a new release? I am a bit hamstrung at the moment.

**Comment by stjepang** [comment] 2019-11-06 23:46
New version has been published now :)

**Closed by stjepang** 2019-11-06 23:46 UTC
