### ISSUE TITLE
trait bounds other than `Sized` on const fn parameters are unstable

### ISSUE THREAD

**Issue by PhillyWebGuy** [crossbeam-rs/crossbeam#807] opened 2022-03-21 02:04 UTC
This package is evidently a dependency of dependency for a repo I am working in. I just ran cargo update, went to compile, and now my code won't compile. I'm pretty new to Rust so I'm sort of at a loss as to what to do right now, particularly since this crate isn't even a dependency listed in any Cargo.toml file, thus I assume it is a dependency of a dependency. 

```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /Users/klptechco/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.8/src/atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `crossbeam-epoch` due to previous error

```

**Comment by cynecx** [comment] 2022-03-21 02:05
Duplicate of https://github.com/crossbeam-rs/crossbeam/issues/803.

**Comment by PhillyWebGuy** [comment] 2022-03-21 02:08
@cynecx Thanks for the quick reply!

**Closed** 2022-03-21 02:08 UTC
