### ISSUE TITLE
crossbeam-epoch compiler error in the nightly channel

### ISSUE THREAD

**Issue by elefthei** [crossbeam-rs/crossbeam#679] opened 2021-04-02 00:24 UTC
Hello,

One of my projects is pulling `crossbeam-epoch-0.9.3` from the `nightly` channel and I am getting this compiler error, looks
like it's coming from here?

```
   Compiling crossbeam-epoch v0.9.3
error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/elefthei/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.3/src/internal.rs:620:59
    |
620 |         let local_ptr = (entry as *const Entry as usize - offset_of!(Local, entry)) as *const Local;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/elefthei/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.3/src/internal.rs:613:59
    |
613 |         let entry_ptr = (local as *const Local as usize + offset_of!(Local, entry)) as *const Entry;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `crossbeam-epoch`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by taiki-e** [comment] 2021-04-02 01:59
duplicate of #678, it can be fixed by using nightly-2021-01-31 or later

**Closed by taiki-e** 2021-04-02 01:59 UTC
